version: "3.4"

services:
  app:
    build: .
    restart: unless-stopped
    volumes:
      - ./:/app
    ports:
      - 3000:3000
    depends_on:
      - database
    env_file:
        - database.env

  database:
    container_name: "postgres-database"
    image: "postgres:13.4"
    restart: unless-stopped
    ports:
      - 5432:5432
    env_file:
        - database.env

  flyway:
    image: flyway/flyway:7.3.0-alpine
    env_file:
      - database.env
    depends_on:
      - database
    volumes:
      - .:/flyway/sql
    command: -connectRetries=60 -baselineOnMigrate=true migrate